### PR TITLE
Update memsmt fodf script [requires dipy 1.8.0]

### PR DESCRIPTION
**Pull request by karanphil**
# Quick description

WIP.

Updating and cleaning the `scil_compute_memsmt_fodf.py` script according to the last Dipy release. Will be testable when this release comes.

## Type of change

Check the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Provide data, screenshots, command line to test (if relevant)

...

# Checklist

- [x] My code follows the style guidelines of this project (run [autopep8](https://pypi.org/project/autopep8/))
- [x] I added relevant citations to scripts, modules and functions docstrings and descriptions
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I moved all functions from the script file (except the argparser and main) to scilpy modules
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-791/1/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-791/2/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by karanphil** [comment]
@mdesco could you quickly test this PR with the data from McGill? After that I think it is good to go.

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Review by arnaudbore — APPROVED** [review]
Waiting for @mdesco tests, otherwise LGTM

**Comment by karanphil** [comment]
> --in_bdeltas argument is not clear to me. What is the correct format for the argparser. Can you provide a clear help or example please.

I added an example of command line in each script.

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Review by arnaudbore — APPROVED** [review]
LGTM

**Pull request merged**
