### PR TITLE
New method to get n seeds at once.

### PR DESCRIPTION
**Pull request by EmmaRenauld**
There you go, @CHrlS98 !  Tell me if it works!

### CODE REVIEW

**Comment by scil-admin** [comment]
Build passed ! Good Job :beers: !

**Review by frheault — COMMENTED** [review]
Is it necessary that all methods only accept one point at a time?

I think this could be a lot more useful if it supported a list of points (or an array, Nx3) and used this function for fast access (even at N=1 I think it is faster)
Bonus:
- and all the _clip functions could be removed
- the vox_to_idx and interpolation could be removed

https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.map_coordinates.html

**Comment by EmmaRenauld** [comment]
Thanks for your bonus ideas, I'll check that.

Yeah, eventually we could probably change all methods! Right now Charles is testing with his own GPU tracker if this method works for him. After, we could proceed to change everything if we think it's efficient. @CHrlS98

**Comment by EmmaRenauld** [comment]
@frheault , map_coordinates uses spline interpolation of order 0-5, whereas our current implementation uses trilinear (or nearest neighbor), isn't it. I think it would be a bigger change that would need to be discussed in another PR, if we wish.

**Comment by frheault** [comment]
I am 99.9% sure order 0 is nearest-neighbor and order 1 is linear.

EDIT: https://stackoverflow.com/questions/57777370/set-interpolation-method-in-scipy-ndimage-map-coordinates-to-nearest-and-bilinea

**Comment by CHrlS98** [comment]
> Is it necessary that all methods only accept one point at a time?
> 
> I think this could be a lot more useful if it supported a list of points (or an array, Nx3) and used this function for fast access (even at N=1 I think it is faster) Bonus:
> 
>     * and all the _clip functions could be removed
> 
>     * the vox_to_idx and interpolation could be removed

@frheault @EmmaRenauld I think we should write an issue for this, to be tackled in a future PR.

**Comment by EmmaRenauld** [comment]
I agree. When both this PR and the other one will be accepted, I will write the issue.

**Comment by EmmaRenauld** [comment]
Issue has been open. Charles, did you test this? Should remove the "draft" of this PR?

**Comment by CHrlS98** [comment]
@EmmaRenauld I did not test it yet. I kinda forgot about it...
It's not a priority for me to be able to seed N times at the moment. You can decide if it is worth merging or if we should simply close the PR and fix the issue instead.

**Comment by scil-admin** [comment]
Build passed ! Good Job :beers: !

**Comment by EmmaRenauld** [comment]
Well, @arnaudbore , this is a method that I use in dwi_ml. Do you want me to move in to scilpy in case we use it one day to track multiple streamlines at the same time?

**Comment by arnaudbore** [comment]
@EmmaRenauld Go !

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-597/3/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-597/4/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-597/5/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Pull request merged**
