### PR TITLE
WIP: ENH: Add Sphinx documentation config files

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add Sphinx documentation config files.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
This is still a first draft. Does not yet generate the package documentation properly. The index looks like this:

scilpy_package_documentation_index

**Comment by boiteaclou** [comment]
If I remember well, there is some package that can generate the autodoc .rst files automatically. Also, since the documentation is written in Numpy/Google format, you'll need to add sphinx.ext.napoleon to sphinx extensions in conf.py

**Comment by jhlegarreta** [comment]
@boiteaclou thanks for having had a look !! I will investigate the suggested aspects in the following days. Thanks again Alex !

**Comment by jhlegarreta** [comment]
The documentation gets successfully generated (with some rough edges -29 warnings) with
```
cd doc
sphinx-apidoc -f -o . ../scilpy
make html
```

which gives:

scilpy_package_documentation_module_index

and

scilpy_package_module_doc_example

**Comment by arnaudbore** [comment]
@jhlegarreta can you find a way this doc would auto build ? Where would it live ? Very interesting way of checking where documentation is missing.

**Comment by jhlegarreta** [comment]
> @jhlegarreta can you find a way this doc would auto build ?

I guess I could find a way to add a GitHub Actions workflow to build the doc for every PR.

I think it would be best to add that automation in a separate PR, since it can spur a somewhat long debate about the burden it may involve, whether it can be triggered only when the doc changes, etc. 

That is to say, I can remove the `WIP` label to this PR and it would be ready to be merged provided that you want to test it locally and works for you. Further improvements and fixes can come afterwards, 

> Where would it live ?

Best would be that an administrator of the organization creates a generic account in readthedocs to host this. I would not host this anybody's personal readthedocs account (even if that person is an admin). Maybe we can even come up with a script that automates generating and pushing the new documentation to readthedocs before a release.

**Comment by GuillaumeTh** [comment]
I find a way to do it automatically on scil-documentation. Otherwise we can create a doc folder like this in this repository

**Comment by arnaudbore** [comment]
Documentation has been merge using #247.

**Pull request closed without merging**
