### PR TITLE
Fix multiprocess in dev tracking

### PR DESCRIPTION
**Pull request by EmmaRenauld**
During multiprocessing Pool, the argument sent is a dict, but the multiprocessing sends it as *args, thus deconstructing the dict.
Modifying to (dict, ), so that instead it will diconstruct the tuple and leave the dict intact.

Not sure how we did not find this bug sooner... Sorry.

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by EmmaRenauld** [comment]
Yes, everything crashed. And I don't understand, me too, I think it worked at some point. But yesterday, I ran it with this modified code and it worked.

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Review by CHrlS98 — APPROVED** [review]
Tested on python3.10; all works well :100:

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Pull request merged**
