### PR TITLE
[ENH] Add new parameter to overwrite filter distance

### PR DESCRIPTION
**Pull request by arnaudbore**

### CODE REVIEW

**Comment by frheault** [comment]
I don't see the use for this if we just added the distance (opt) parameter.

This script is already a monster of complexity, so why not just use that new behavior you just added?

**Comment by arnaudbore** [comment]
> I don't see the use for this if we just added the distance (opt) parameter.
> 
> This script is already a monster of complexity, so why not just use that new behavior you just added?

I understand but this parameter will allow you to not take care of the distance individually and just force any either_end both_end to a specific distance. It is specially interesting with a lot of filtering lists you don't want to modify each time you run a test.

**Comment by frheault** [comment]
Compromise: why not having an argument `--overwrite_distance 'mode' 'distance'` (nargs='+') that can overwrite the type of filtering of your choice (and not just _ends_)

With check that you don't accidentally write `--overwrite_distance any 1 --overwrite_distance either_end 2 --overwrite_distance any 3` (writing the same mode twice)

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-723/4/

**Review by frheault — APPROVED** [review]
I tested it with 3 BDO and 1 NIFTI to segment an AF and it worked well!

**Pull request merged**
