### PR TITLE
Add multiple fs folder subject possibility

### PR DESCRIPTION
**Pull request by arnaudbore**
Before that PR Freesurfer folder had to be name the same way as the subject now it can include the session.

Ex:
```
bids - sub-001/ses-1/
     - sub-001/ses-2/
```
and
```
fs - sub-001
or
fs - sub-001_ses-1
   - sub-001_ses-2
```

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Review by AntoineTheb — APPROVED** [review]
Besides pep8 errors, LGTM

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Pull request merged**
