### PR TITLE
Testing 3 10 upgrade

### PR DESCRIPTION
**Pull request by frheault**

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-662/1/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-662/2/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-662/3/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-662/4/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-662/5/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-662/6/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-662/7/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-662/9/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-662/11/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Review by EmmaRenauld — CHANGES_REQUESTED** [review]
One of my scripts fails with:

In scilpy.tracking.tools:
from scipy.ndimage.filters import gaussian_filter1d:

DeprecationWarning: Please use `gaussian_filter1d` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.

**Comment by frheault** [comment]
@EmmaRenauld but that's a warning, should not be a problem?
I can do a PR next week (after testing the flows) that will fix the DeprecationWarning (and other critical warnings).

**Comment by EmmaRenauld** [comment]
Yeah sorry. Not fails. Sends a warning.

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by EmmaRenauld** [comment]
In my new python 3.10 environment, this fails:
```
import matplotlib.pyplot as plt
f = plt.figure()
plt.show()
```
with explanation `UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.`

plt.savefig works, but not plt.show. For instance, this fails: `scil_visualize_histogram.py [...] --show_only`

[Here](https://stackoverflow.com/questions/56656777/userwarning-matplotlib-is-currently-using-agg-which-is-a-non-gui-backend-so), suggestion 1 is to do: `sudo apt-get install python3-tk`, but it was already installed in my case. What worked for me is another suggestion below: `pip install PyQt5`

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by frheault** [comment]
> In my new python 3.10 environment, this fails:
> 
> ```
> import matplotlib.pyplot as plt
> f = plt.figure()
> plt.show()
> ```
> 
> with explanation `UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.`
> 
> plt.savefig works, but not plt.show. For instance, this fails: `scil_visualize_histogram.py [...] --show_only`
> 
> [Here](https://stackoverflow.com/questions/56656777/userwarning-matplotlib-is-currently-using-agg-which-is-a-non-gui-backend-so), suggestion 1 is to do: `sudo apt-get install python3-tk`, but it was already installed in my case. What worked for me is another suggestion below: `pip install PyQt5`

Thats something fixed in the singularity and true in python3.*. The backend has to be switch from Agg to TkAgg
https://stackoverflow.com/a/34294056

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Pull request merged**
