### PR TITLE
Cleaning reconst module

### PR DESCRIPTION
**Pull request by karanphil**
I applied the following modifications to the module scilpy.reconst (and other modules impacted):

scilpy.reconst:

- divide_fit.py renamed divide.py
- multi_processes.py:
fit_from_model moved to fodf.py
peaks_from_sh, maps_from_sh, convert_sh_basis, convert_sh_to_sf moved to sh.py
fit_gamma moved to divide.py
multi_processes.py has been removed

- afd_along_streamlines.py and lobe_metrics_along_streamlines.py moved to scilpy.tractanalysis
- raw_signals.py:
compute_dwi_attenuation moved to scilpy.dwi.operations.py
raw_signals.py renamed dwi.py

- b_tensor_utils.py moved to scilpy.io.b_tensor.py
- docs.source.modules was updated for reconst.

scilpy.dwi:

- new: operations.py
- rescale_dwi (and _rescale_intensity) moved from utils.py to operations.py

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-806/1/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Review by mdesco — APPROVED** [review]
Good job! Tested all scripts except the b-tensor encoding stuff... Did not have b-tensor data at hand...

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-806/5/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-806/4/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Review by EmmaRenauld — APPROVED** [review]

**Review by arnaudbore — APPROVED** [review]
GTG

**Pull request merged**
