### PR TITLE
adding vtk legacy options to scil_convert_surface script

### PR DESCRIPTION
**Pull request by ThoumyreStanislas**
I've modified the scil_convert_surface script so that surfaces created by freesurfer can be viewed in MI-Brain and aligned with T1. An updated version of trimeshpy is required for the script to work, but is not yet available.

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-795/1/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-795/2/

**Comment by ThoumyreStanislas** [comment]
I've corrected the code and moved the xform and flip_LPS functions to the scilpy/utils/util.py module.

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-795/4/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-795/7/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-795/10/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Review by arnaudbore — APPROVED** [review]
Gooodddd !!!

**Pull request merged**
