### PR TITLE
Rename small utils

### PR DESCRIPTION
**Pull request by EmmaRenauld**
A small PR!

   (scil_validate_bids--> deleted the commit, Arnaud will manage)
scil_print_header
scil_validate_space_attribute_comptability
scil_convert_fdf

### CODE REVIEW

**Review by arnaudbore — APPROVED** [review]
LGTM

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-852/1/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-852/2/

**Review by AntoineTheb — APPROVED** [review]
LGTM

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Pull request merged**
