### PR TITLE
Adding tolerance argument to fodf msmt

### PR DESCRIPTION
**Pull request by karanphil**
Addressing issue #830 from @mdesco , I added a tolerance argument to `scil_fodf_msmt.py`. It was simply hardcoded to tol=20 in one function, and set to default (20) in another. This was in fact a potential breaking point even if it ran. I just had to give the option.

@mdesco could you try to run it again on your setup? Thanks!

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-839/1/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-839/2/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Review by mdesco — APPROVED** [review]

**Pull request merged**
