### PR TITLE
Make stopping criteria  more obvious + more similar to dipy.

### PR DESCRIPTION
**Pull request by EmmaRenauld**
In the tracking dev, manage the stopping criteria as in Dipy:

- If direction is invalid (angle or ODF threshold): do not add the next point.
     - (Previous usage was to add an additional straight point instead)
- Else, if out of tracking mask: the point is added, and *then* the streamline is stopped.
    - (Was already like that, but out of the for loop).

Add this choice to doc so that it is more obvious for the user.

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by EmmaRenauld** [comment]
(rebased on #714, waiting for thi s to be merged)

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by EmmaRenauld** [comment]
Rebased

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Pull request merged**
