### PR TITLE
Exploration for python3.10 switch (WIP)

### PR DESCRIPTION
**Pull request by frheault**
@arnaudbore This is just a reference to see what is required for the transition to 3.10.

Based on my computer (Mint21, Ubuntu22), created an environment in 3.8, 3.9, and 3.10.
I updated all libraries to see what happens when they all are left to their most recent version.
(We were VERY late behind a few. I need to run all flows and look at the results to identify problems)

This is just a PR to compare what could be updated.

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-660/1/

**Comment by frheault** [comment]
This was a test mostly for SPAMS, AMICO, AMICO, DIPY, to see if we need to do PR in these before we update SCILPY later.

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-660/2/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-660/3/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-660/4/

**Pull request closed without merging**
