### PR TITLE
Adding a cut streamlines tools

### PR DESCRIPTION
**Pull request by frheault**
Using either a binary mask with 1 or 2 blob, cut streamlines accordingly.

Filters streamlines and only keeps the parts of streamlines within or
between the ROIs. The script accepts a single input mask, the mask has either
1 entity/blob or 2 entities/blobs.

The 1 entity scenario will 'trim' the streamlines so their longest segment is
within the bounding box or a binary mask.

The 2 entities scenario will cut streamlines so their segment are within the
bounding box or going from binary mask #1 to binary mask #2.

### CODE REVIEW

**Comment by scil-admin** [comment]
Build passed ! Good Job :beers: !

**Comment by scil-admin** [comment]
Build passed ! Good Job :beers: !

**Review by mdesco — COMMENTED** [review]
Minor text edit and then all good for me!

**Comment by scil-admin** [comment]
Build passed ! Good Job :beers: !

**Review by arnaudbore — APPROVED** [review]
Need a test otherwith LGTM

**Comment by scil-admin** [comment]
Build passed ! Good Job :beers: !

**Pull request merged**
