### PR TITLE
add mti.py in reconst

### PR DESCRIPTION
**Pull request by Manonedde**
Copy MTI functions to reconst.mti.py.
@mdesco @karanphil

### CODE REVIEW

**Review by mdesco — APPROVED** [review]

**Comment by EmmaRenauld** [comment]
Hi! 

Can you try to improve right now the pep8 a little? Then I'll ask Arnaud to merge!

**Review by karanphil — APPROVED** [review]

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Review by mdesco — APPROVED** [review]

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-768/4/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Pull request merged**
