### PR TITLE
Simple framework to port scripts into legacy

### PR DESCRIPTION
**Pull request by AlexVCaron**
Legacy scripts are added to the setup directly in version.py. We have to decide how long the use of a deprecated script remains correct. Since it is interface breaknig for our user, I would remove them when the next `major` version comes out.

To port a script into legacy :

1. Move the script into scripts/legacy
2. `from scilpy.io.deprecator import deprecate_script`
3. Create a deprecation message : `DEPRECATION_MSG = "..."`
4. Decorate the main :
   ```python
   @deprecate_with_version(DEPRECATION_MSG, "<version when deprecation starts>")
   ```

For now, build will succeed even if there is outdated legacy scripts in the repository. However, they won't be executable (will raise an error by default). I will investigate in `setuptools` to find a way to do it.

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-807/1/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-807/2/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-807/4/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-807/5/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-807/6/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by EmmaRenauld** [comment]
Tested on an upcomping branch on mine to deprecate the scil_streamline_math (already deprecated, but without the decorator).

(P.S. the description of this PR should read: the decorator of the main is @deprecate_script)

Works! Questions:
- Here is the result: 
    - It says dipy error. Ok? 
    - It says: "as of version 2.0.0" although I used 1.7.0. 
    - Anyway to hide the sys.exit()?
    - The warning only appears at the top of the help. So if users doesn't go back up (ex, after printing the whole help), he won't see it. ok for us?

deprecated

**Comment by arnaudbore** [comment]
I think it would make more sense if @AlexVCaron you put scil_streamline_math script example in this PR.

**Comment by EmmaRenauld** [comment]
https://github.com/EmmaRenauld/scilpy/tree/deprecate_streamline_math

**Comment by AlexVCaron** [comment]
I added the script. Do we keep a long expiration window on the version major ? Or we shorten it by targeting 2 or 3 minor revisions ahead ?

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Pull request merged**
