### PR TITLE
Update to dipy 1.8

### PR DESCRIPTION
**Pull request by arnaudbore**

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-853/1/

**Comment by frheault** [comment]
Switch nibabel==4.* to 5.*

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-853/2/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-853/3/

**Comment by frheault** [comment]
File `scilpy/image/tests/test_labels.py`, test `test_get_data_as_labels_int`:
Line 107 `img = nib.Nifti1Image(data, np.eye(4))` should become `img = nib.Nifti1Image(data, np.eye(4), dtype=np.int64)`

This will have to become a part of our routine when saving as int64, which is rare. We mostly save as uint8 (mask) uint16 (labels) or float32/float64 for everything else.

(I also updated with master, everything seems to work)

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-853/5/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by EmmaRenauld** [comment]
Do we need to change something in the README? I don't think we need to install stuff before anymore, like
pip install packaging>=19.0
pip install numpy==1.23.*
pip install Cython==0.29.*


(I didn't and it worked, locally)

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Pull request merged**
