### PR TITLE
Fixing uniform_coloring in scil_visualize_bunldes.py

### PR DESCRIPTION
**Pull request by karanphil**
Just a quick fix of the `uniform_coloring` option in `scil_visualize_bunldes.py`. The color was given in RGB (in range [0, 255]) but the viewer used range [0, 1], so I kept the 0 to 255 as input and divided by 255 before feeding it to the viewer. @AntoineTheb

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Review by AntoineTheb — APPROVED** [review]
Thanks for the fix @karanphil, LGTM

**Comment by frheault** [comment]
@karanphil Can you update this code with master and then check if everything runs normally.
The master is now up to 3.10 (but should run in 3.8/3.9), so you may have to create a new venv.

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by karanphil** [comment]
> 

Works fine with python 3.10!

**Review by frheault — APPROVED** [review]

**Pull request merged**
