### PR TITLE
Rename some tractogram scripts

### PR DESCRIPTION
**Pull request by EmmaRenauld**
A small PR!

Three renaming tractogram_:

scil_compute_todi.py --> scil_tractogram_compute_TODI
scil_compute_streamlines_length_stats.py --> scil_tractogram_print_info   (With added capacities)
scil_compute_streamlines_density_map.py --> tractogram_compute_density_map

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-846/1/

**Comment by frheault** [comment]
Maybe remove the compute from the filename?

convert or filter are specific verb, it is true compute is non specific.

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-846/2/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-846/4/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Review by arnaudbore — APPROVED** [review]
GTG

**Pull request merged**
