### PR TITLE
Add option to scale SF by the b0 in scil_compute_sf_from_sh.py

### PR DESCRIPTION
**Pull request by ppoulin91**
Add option to scale SF by the given b0, to be symmetrical with `scil_compute_sh_from_signal.py` when using `--use_attenuation`
- Requires a b0 to be given as input
- Fixes a bug where bvecs corresponding to b0 images are not removed before building the sphere, causing additional bvecs to be created when normalizing the "b0-bvecs"

### CODE REVIEW

**Comment by scil-admin** [comment]
Build passed ! Good Job :beers: !

**Comment by scil-admin** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-545/2/

**Comment by scil-admin** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-545/3/

**Comment by scil-admin** [comment]
Build passed ! Good Job :beers: !

**Review by mdesco — APPROVED** [review]
All good for me.

**Review by arnaudbore — COMMENTED** [review]
Quick comments.

**Comment by scil-admin** [comment]
Build passed ! Good Job :beers: !

**Pull request merged**
