### PR TITLE
[BF] Update bundle metrics - handle NaN

### PR DESCRIPTION
**Pull request by arnaudbore**

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Review by CHrlS98 — APPROVED** [review]
Code looks good to me !

**Review by frheault — APPROVED** [review]

**Pull request merged**
