### PR TITLE
Update to hotdipy + fix load empty sft

### PR DESCRIPTION
**Pull request by arnaudbore**
To test: 
scil_tractogram_math.py union t0003__in_AC_Cx_f.trk t0003__in_CC_BG_f.trk toto.trk -f
[trk.tar.gz](https://github.com/scilus/scilpy/files/10992916/trk.tar.gz)

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-694/3/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-694/4/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Review by AlexVCaron — APPROVED** [review]
All passing in the container !

**Pull request merged**
