### PR TITLE
Display masks as contours in screenshots

### PR DESCRIPTION
**Pull request by AlexVCaron**
Add capabilities to display mask overlays as contour instead of transparency. Integration into mosaic overlay script and new script to create multiple screenshots from one volume. Multiple examples are provided in the scripts documentation for tests.

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by AntoineTheb** [comment]
Nice ! Do you have data to test this ?

**Comment by AlexVCaron** [comment]
[Here](https://usherbrooke-my.sharepoint.com/:u:/g/personal/vala2004_usherbrooke_ca/EZ6a8NTKmEBIjZEyh5k84qoBi_HA96AJV-5IS1gozngcqw?e=BKRqXS) you go ! You can try it with pretty much any data with masks you have though.

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Is there a way to make these 2 scripts more lookalike (more similar args) ? Can you add an option to add if wanted the number of each slice and L-R position ?

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by AlexVCaron** [comment]
[Here is a small script](https://usherbrooke-my.sharepoint.com/:u:/g/personal/vala2004_usherbrooke_ca/Eae3RHFdxUhJimiLe-i6lbMBGGbBmA74x-4KVrNUkq0zYw?e=G9YOZz) to test all the parameters variations of both screenshotting scripts. You have to supply a few files, defined in the script at the top.

**Pull request merged**
