### PR TITLE
[WIP][NF] script to search databases

### PR DESCRIPTION
**Pull request by GuillaumeTh**
New script to search databases.

You must to have your braindata mounted in /braindata or use the --csv option with the path to your braindata/utils/databases.csv

### CODE REVIEW

**Comment by Manonedde** [comment]
Test for Braindata with --csv path, no error detected.

Can I suggest a search option that I think is important ?
  -- patho with MS, concussion, stroke, AD, ... in database.csv

Maybe others a little less important but which could be useful:
- "source" of the database: public (HCP, UKBiobank) or specific to the lab (HOG, Myelo-inferno)
- Multimodality option (like is_healthy) if there is FC, TEP, Myelin or Vascu in addition to the diffusion acquisition 
- T of MRI: 1.5T?, 3T or 7T
- Machine: GE, Philips, Siemens ...?

**Comment by arnaudbore** [comment]
I agree with @Manonedde we need a lot more information about the databases but also we need a way to add a new database. Maybe it would be more secure / flexible with sql lite. In addition to what @Manonedde suggested I would also add:
- number of shells
- number of dirs
- number of groups

**Review by mdesco — COMMENTED** [review]
If I run the script just like this:
scil_search_database.py

I get tones of errors. Can I just get the usual help print from our scilpy scripts please?

**Comment by mdesco** [comment]
Cool stuff guys. The databases.csv seems WIP, correct?
Please remove the NaNs and put all you can. I can help. Just ask

**Comment by mdesco** [comment]
@arnaudbore are we going to put a databases.csv in rrg-descotea/datasets?

**Comment by scil-admin** [comment]
Build passed ! Good Job :beers: !

**Pull request closed without merging**
