### PR TITLE
BF: Modify vtk version for >=8.1.0

### PR DESCRIPTION
**Pull request by GuillaumeTh**
Modify vtk version for >=8.1.0 for python 3.7. Solve issue #45

### CODE REVIEW

**Comment by arnaudbore** [comment]
@mdesco can you give it a try on your mac ?

**Comment by EmmaRenauld** [comment]
I tried with a brand new environment. I didn't get to test vtk because of issues with numpy first. I remember having the same issue when installing with python3.5. Doesn't seem to be fixed.

-- During pip install -r requirements: 
scipy error because of numpy. (Whole error in attached file.
[error_scipy.txt](https://github.com/scilus/scilpy/files/3952261/error_scipy.txt) )

-- During scilpy's python setup.py install: 
fatal error: numpy/arrayobject.h: No such file or directory
error: command 'gcc' failed with exit status 1

(Note. I tried with pip install -e . : didn't work either. Also because of numpy.)

Using numpy==1.17.4 does not solve the error
Using numpy==1.17.4 and scipy==1.3.3 solve the requirements error but not the installation error.

**Comment by EmmaRenauld** [comment]
New update. There was an error in setup.py. @StongeEtienne should be doing a PR.

```
Extension('scilpy.tractanalysis.quick_tools',
                        `['scilpy/tractanalysis/quick_tools.pyx']),
```

should be

```
Extension('scilpy.tractanalysis.quick_tools',
                        ['scilpy/tractanalysis/quick_tools.pyx'],
                        include_dirs=[numpy.get_include()]),
```

So:
Using numpy==1.17.4 and scipy==1.3.3
+ changing setup.py
+ changing vtk>=

Works and installs vtk 8.1.2. I have not tested any script though.

**Comment by arnaudbore** [comment]
Closing this PR since we only have one function that uses vtk and it's not even used. I will add a PR removing these few lines.

**Comment by StongeEtienne** [comment]
@arnaudbore fury (fury-gl) 0.2.0 is required in this project and use (in the current requirement)
vtk>=8.1.0

fury 0.4.0 updated it to
vtk>=8.1.2

vtk is used for surface, and .fib format (now in dipy)
and currently the install with the current requiremnents.txt is not worrking for python 3.7

**Pull request closed without merging**
