### PR TITLE
Gradient sampling ajustment

### PR DESCRIPTION
**Pull request by karanphil**
Very small change in the `scil_generate_gradient_sampling.py` script, in order to get a gradient table readable by a Philips scanner. Indeed, Philips scanners require that the gtab have unique pairs of bvecs and bvals for each line. By default, the script outputs the same pair of bvecs [0, 0, 0] and bvals [0] for each bvals in the gtab. The added option simply copies the bvecs from the previous line for each bvals, except the first one.

To test this, simply run the script, for example `scil_generate_gradient_sampling.py 16 32 64 dwi --eddy --duty --b0_every 18 --bvals 500 1000 2000 --mrtrix --b0_philips`, and make sure that no b0 has the same bvecs.

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Review by EmmaRenauld — APPROVED** [review]
Tested with an without --b0_philips. Works, thanks!


p.s. For future work. Wouldn't we want to add a rng seed option to be able to produce twice the same result?

**Comment by arnaudbore** [comment]
@EmmaRenauld can you add an issue about improving this with a rng seed option ?

**Pull request merged**
