### PR TITLE
Custom ROI surface rendering for Laurent

### PR DESCRIPTION
**Pull request by frheault**
Simple features for Laurent that allow you to add ROI (and colors) to the screenshot tools.
It is called like this: `scil_screenshot_bundle.py atlas/pop_average/AF_L.trk mni_masked.nii.gz  --roi a.nii 255 0 0 --roi b.nii 0 255 0 --roi c.nii 0 0 255  -f`

sagittal_3d

There is 3 mode, the simplest shows the ROI as white, but if you specify RGB or RGBA after you can pick the color
```
For the --roi argument: If 1 value is provided, the ROI will be white,
if 4 values are provided, the ROI will be colored with the RGB values
provided, if 5 values are provided, it is RGBA (values from 0-255).
```

If the user use the wrong number of value (1, 4 or 5 is accepted) you get `--roi must be used either with PATH or with PATH R G B  or PATH R G B A`

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Comment by frheault** [comment]
@arnaudbore Laurent is curious about the script. Do you want to try it out first? Or I can merge?

**Comment by arnaudbore** [comment]
Merge, we have a week before release.

Le dim. 1 oct. 2023, 09 h 33, Francois Rheault ***@***.***> a
écrit :

**Pull request merged**
