### PR TITLE
Fix lazy usage with tck files

### PR DESCRIPTION
**Pull request by EmmaRenauld**
Fix case where output is a tck and at least one input was trk: wrong header.

### CODE REVIEW

**Comment by scil-admin** [comment]
Build passed ! Good Job :beers: !

**Comment by EmmaRenauld** [comment]
Ready, @frheault ! Thanks again!

**Comment by scil-admin** [comment]
Build passed ! Good Job :beers: !

**Comment by scil-admin** [comment]
Build passed ! Good Job :beers: !

**Review by frheault — APPROVED** [review]

**Pull request merged**
