### PR TITLE
Fix round_bvals_to_shell

### PR DESCRIPTION
**Pull request by karanphil**
Simple fix for `scilpy.gradients.bvec_bval_tools.round_bvals_to_shell` function using `get_bval_indices` from Dipy. I also removed `get_shell_indices` from scilpy since it was the same as the Dipy function.

I did not touch the identify_shells function.

### CODE REVIEW

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-811/1/

**Review by EmmaRenauld — APPROVED** [review]

**Review by arnaudbore — APPROVED** [review]
LGTM

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-811/2/

**Comment by arnaudbore** [comment]
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-811/3/

**Comment by arnaudbore** [comment]
Build passed ! Good Job :beers: !

**Pull request merged**
